import assert from 'node:assert/strict';
import { flatSight } from '../js/sight.js';
import { newGame, activate, weaponsFor, shootCheck, resolveShoot } from '../js/game.js';
const a = { x: 0, y: 0 }, b = { x: 10, y: 0 };
const sight = (terrain, opts = {}, target = b) => flatSight(terrain, a, target, .5, .5, opts);
const cover = { kind: 'light', x: 8.7, y: -.25, w: .2, h: .5 };
const middle = { kind: 'heavy', x: 5, y: -.2, w: .4, h: .4 };
assert.equal(sight([]).cover, false);
assert.equal(sight([cover]).cover, true, 'Any crossing part of the facing-base fan gives cover');
assert.equal(sight([{ ...cover, y: 2 }]).cover, false, 'Nearby terrain outside the fan gives no cover');
assert.equal(sight([middle]).visible, true, 'Visible around the edge of a heavy feature');
assert.equal(sight([middle]).obscured, true, 'Intervening heavy parts more than 1 inch from both bases obscure');
assert.equal(sight([{ ...middle, x: 1, w: .1, y: -.05, h: .1 }]).obscured, false, 'Intervening parts close to shooter do not obscure');
assert.equal(sight([{ ...middle, y: -2, h: 4 }]).visible, false, 'An opaque wall hiding the whole model blocks visibility');
assert.equal(sight([{ ...middle, y: -2, h: 4, blocksSight: false }]).visible, true, 'Open heavy feature can obscure without blocking model visibility');
assert.deepEqual(sight([cover, middle]).defenceOptions, [{ cover: true, obscured: true }], 'Separate terrain benefits stack');
const long = { kind: 'heavy', blocksSight: false, x: 1, y: -.1, w: 8, h: .2 };
const shared = sight([long]);
assert.equal(shared.cover, true); assert.equal(shared.obscured, true);
assert.equal(shared.defenceOptions.length, 2, 'Only the same feature forces a choice');
assert.equal(sight([cover], { ignoreLight: true }).cover, false);
assert.equal(sight([middle], { noObscure: true }).obscured, false);
assert.equal(sight([{ kind: 'light', x: 1.5, y: -.4, w: .1, h: .8 }], {}, { x: 2.5, y: 0 }).cover, false, 'Within 2 inches ignores cover');

const g = newGame({ teams: ['angels', 'kommandos'], ai: null });
g.phase = 'firefight'; g.tp = 1; g.turn = 0;
g.ops.forEach(o => { o.x = -100; o.y = -100; });
const op = g.ops.find(o => o.side === 0 && o.tplId === 'sniper'), target = g.ops.find(o => o.side === 1);
Object.assign(op, a, { order: 'engage' }); Object.assign(target, b, { order: 'conceal' }); activate(g, op);
g.terrain = [cover];
const w = weaponsFor(g, op).find(w => w.id === 'sniperMortis');
assert.equal(shootCheck(g, op, target, w).ok, false, 'Conceal + cover is not a valid target');
assert.equal(shootCheck(g, op, target, { ...w, rules: { ...w.rules, seekLight: true } }).ok, true);
assert.equal(shootCheck(g, op, target, { ...w, rules: { ...w.rules, saturate: true } }).ok, false, 'Saturate removes saves, not Conceal protection');
target.order = 'engage';
assert.equal(shootCheck(g, op, target, w).ok, true, 'Engage in cover remains targetable');
g.terrain = [cover, middle];
Math.random = () => .4; // Ordinary hits/saves, no critical or reroll side effects.
const result = resolveShoot(g, op, w, target);
assert.equal(result.inCover, true);
assert.equal(result.obscured, true);
assert.equal(result.coverOrObscured, false, 'Result panel must report stacked benefits, not a choice');
console.log('Shooting visibility, base fans, cover, obscuring, terrain choices and Seek/Saturate checks passed');
